# -*- coding: utf-8 -*-
"""Connection_to_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15L9g9GMffXe5NIC6JlF3YoczxxXm40-w
"""

# Dependencies
import numpy as np
import pandas as pd

# Python SQL toolkit and Object Relational Mapper
import pyodbc
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import psycopg2

from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:group8database@dataco-shipment-data.cbjnopf5cvnq.us-east-2.rds.amazonaws.com:5432/postgres')
# reflect an existing database into a new model
Base = automap_base()

# reflect the tables
Base.prepare(engine, reflect=True)

# Create our session (link) from Python to the DB
session = Session(engine)

connection = engine.connect()

dataco_dataset= pd.read_sql_query("SELECT * FROM orders INNER JOIN product ON orders.product_card_id = product.product_card_id INNER JOIN customer ON orders.customer_id = customer.customer_id", connection)

dataco_dataset